apiVersion: v1
kind: Service
metadata:
  name: sms-service
  namespace: sms-namespace
spec:
  type: NodePort
  selector:
    app: sms
  ports:
    - port: 8100          # container's port
      targetPort: 8100
      nodePort: 30080     # exposed externally on localhost